---
# This task gets poe fan speed levels on distros where poe params are configured by udev (i.e Ubuntu)

- name: get cpu temp trip points
  shell: cat /etc/udev/rules.d/50-rpi-fan.rules | grep ATTR | awk 'BEGIN { FS =  "="} ; {print $2}'
  register: trip_results

- name: poe fan trip point results
  debug:
    msg:
      - tp3 temp: {{trip_results.stdout_lines[0]}}
      - tp3 hyst: {{trip_results.stdout_lines[1]}}
      - tp2 temp: {{trip_results.stdout_lines[2]}}
      - tp2 hyst: {{trip_results.stdout_lines[3]}}
      - tp1 temp: {{trip_results.stdout_lines[4]}}
      - tp1 hyst: {{trip_results.stdout_lines[5]}}
      - tp0 temp: {{trip_results.stdout_lines[6]}}
      - tp0 hyst: {{trip_results.stdout_lines[7]}}
